### PR TITLE
Add syntax highlighting

### PR DESCRIPTION
**Pull request by cmontella**

### CODE REVIEW

**Comment by ibdthor** [comment]
no highlighting for datalog, a la nov 5 2014 post

**Comment by joshuafcole** [comment]
we don't have a highlighter for the SMIL syntax, though IIRC I wrote it to
look like valid clojure and edited it in clojure mode.

**Comment by ibdthor** [comment]
i don't know if it's datalog or what, but the queries from dec 1 2014 and april 22 2015 are also unhighlighted

**Comment by ibdthor** [comment]
no highlighting on jun 22 2016 post

**Comment by ibdthor** [comment]
no highlighting on jun 30 2016 post

**Comment by joshuafcole** [comment]
Only the latest eve syntax will be highlighted, we older ones should continue being plain text. Gotta make sure they aren't accidentally being *weirdly* highlighted by the new guy, and that no non-eve code like JS is being highlighted strangely either.

**Comment by ibdthor** [comment]
inconsistent highlighting on jul 21 2016 post; some #tags are highlighted blue, others are not

**Comment by ibdthor** [comment]
inconsistent highlighting on aug 31 2016 post; some tags are highlighted, others are not; some sin[] fn names are highlighted, others are not; if sin[] as a fn is highlighted, count[] probably should be as well but are not

**Comment by cmontella** [comment]
> inconsistent highlighting on jul 21 2016 post; some #tags are highlighted blue, others are not

This is because the highlighter doesn't detect partial Eve code (outside of a search/bind/commit context)

**Comment by joshuafcole** [comment]
Is there a reason not to update those snippets to make them copy-pastable chunks of Eve?

**Comment by ibdthor** [comment]
partial eve code should probably get highlighting so they look the same inside a block as well as standing alone

**Comment by cmontella** [comment]
They were in the context of the clock example, where we presented a block, and then broke it down step by step.

I really don't want to spend too much time updating old code in our blog for syntax highlighting.

**Comment by joshuafcole** [comment]
I guess I can make an eve-snippet mode that treats everything as legit for the highlighter to use..? The reason why it doesn't highlight the snippet case is for the editor -- brackets outside of a search or action *really* are not a record, and it'd be much harder to notice that with all the visual cues acting as though they were.

**Review by ibdthor — APPROVED** [review]

**Review by joshuafcole — APPROVED** [review]

**Pull request merged**
